ALTER TABLE chat_members ADD COLUMN IF NOT EXISTS can_delete_messages BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE chat_members ADD COLUMN IF NOT EXISTS can_pin_messages BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE chat_members ADD COLUMN IF NOT EXISTS can_add_members BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE chat_members ADD COLUMN IF NOT EXISTS can_edit_info BOOLEAN NOT NULL DEFAULT TRUE;
